import type { BriefResult, NicheIdea } from "./types.js";
import { scoreRecords } from "./scoring.js";

export interface AiOptions {
  useAi?: boolean;
  model?: string;
  apiKey?: string;
}

interface ChatCompletionResponse {
  choices?: Array<{ message?: { content?: string } }>;
  error?: { message?: string };
}

export async function generateBrief(keyword: string, related: string[], options: AiOptions = {}): Promise<BriefResult> {
  if (options.useAi && resolveApiKey(options)) {
    const prompt = `Create a concise research/content brief for this topic: "${keyword}".\n\nRelated phrases: ${related.join(", ") || "none"}\n\nReturn structured markdown with: title ideas, meta description, audience intent, outline, questions to answer, and success metrics.`;
    const content = await callOpenAiText(prompt, options);
    return {
      keyword,
      related,
      format: "markdown",
      content,
      generatedBy: "openai"
    };
  }

  const titles = makeTitleIdeas(keyword);
  const meta = `A practical guide to ${keyword}${related.length ? `, including ${related.slice(0, 3).join(", ")}` : ""}.`;
  const outline = [
    `What ${keyword} means`,
    `Who needs ${keyword}`,
    `Options, tradeoffs, and selection criteria`,
    `Common mistakes and questions`,
    `Next steps and resources`
  ];
  const brief = {
    titleIdeas: titles,
    metaDescription: meta.slice(0, 155),
    audienceIntent: inferAudienceIntent(keyword, related),
    outline,
    questions: [
      `What is ${keyword}?`,
      `How do you choose the right ${keyword}?`,
      `What are the main risks or constraints?`
    ],
    relatedKeywords: related,
    wordCountTarget: related.length >= 5 ? "1800-2400" : "1200-1800"
  };

  return {
    keyword,
    related,
    format: "json",
    content: brief,
    generatedBy: "template"
  };
}

export async function discoverNiches(domain: string, count: number, options: AiOptions = {}): Promise<NicheIdea[]> {
  if (options.useAi && resolveApiKey(options)) {
    const prompt = `Generate ${count} specific niche ideas for the broad domain "${domain}". Focus on specific audiences, emerging demand, monetization potential, and lower competition. Return JSON only with shape {"niches":[{"niche":"...","reason":"..."}]}.`;
    const text = await callOpenAiText(prompt, options, { type: "json_object" });
    const parsed = parseJsonObject(text);
    const items = Array.isArray(parsed?.niches) ? parsed.niches : [];
    return items.slice(0, count).map((item: unknown) => {
      const object = typeof item === "object" && item !== null ? (item as Record<string, unknown>) : { niche: String(item) };
      const niche = String(object.niche ?? object.name ?? object.keyword ?? "").trim();
      const reason = String(object.reason ?? object.summary ?? "Generated by OpenAI.").trim();
      return { niche, reason, score: heuristicNicheScore(niche), generatedBy: "openai" as const };
    }).filter((item) => item.niche);
  }

  const modifiers = [
    "for beginners",
    "for remote teams",
    "for creators",
    "for local businesses",
    "for budget buyers",
    "for compliance-heavy teams",
    "for parents",
    "for seniors",
    "for solo founders",
    "for enterprise operations",
    "for agencies",
    "for hobbyists"
  ];
  const useCases = [
    "templates",
    "automation",
    "training",
    "marketplaces",
    "analytics",
    "consulting",
    "communities",
    "toolkits"
  ];

  const candidates: string[] = [];
  for (const modifier of modifiers) {
    candidates.push(`${domain} ${modifier}`);
  }
  for (const useCase of useCases) {
    candidates.push(`${domain} ${useCase}`);
  }

  const scored = scoreRecords(candidates.map((phrase, sourceIndex) => ({ phrase, sourceIndex, raw: { phrase } })));
  return scored.slice(0, count).map((record) => ({
    niche: record.phrase,
    score: record.score,
    reason: `Text-only opportunity score favors ${record.intent} intent and ${record.wordCount}-word specificity. Add demand/friction columns or --ai for stronger validation.`,
    generatedBy: "template"
  }));
}

function heuristicNicheScore(niche: string): number {
  const [record] = scoreRecords([{ phrase: niche, sourceIndex: 0, raw: { phrase: niche } }]);
  return record?.score ?? 0;
}

async function callOpenAiText(prompt: string, options: AiOptions, responseFormat?: Record<string, unknown>): Promise<string> {
  const apiKey = resolveApiKey(options);
  if (!apiKey) {
    throw new Error("OPENAI_API_KEY is not set.");
  }

  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      authorization: `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: options.model ?? "gpt-4o-mini",
      messages: [{ role: "user", content: prompt }],
      temperature: 0.7,
      ...(responseFormat ? { response_format: responseFormat } : {})
    })
  });

  const payload = (await response.json()) as ChatCompletionResponse;
  if (!response.ok) {
    throw new Error(payload.error?.message ?? `OpenAI request failed with HTTP ${response.status}`);
  }

  const content = payload.choices?.[0]?.message?.content;
  if (!content) {
    throw new Error("OpenAI response did not include message content.");
  }
  return content;
}

function resolveApiKey(options: AiOptions): string | undefined {
  return options.apiKey ?? process.env.OPENAI_API_KEY;
}

function parseJsonObject(text: string): Record<string, unknown> | undefined {
  try {
    return JSON.parse(text) as Record<string, unknown>;
  } catch {
    const match = text.match(/\{[\s\S]*\}/u);
    return match ? (JSON.parse(match[0]) as Record<string, unknown>) : undefined;
  }
}

function makeTitleIdeas(keyword: string): string[] {
  const normalized = keyword.trim();
  return [
    `${titleCase(normalized)}: Practical Guide`,
    `How to Choose ${titleCase(normalized)}`,
    `${titleCase(normalized)} Options Compared`
  ];
}

function inferAudienceIntent(keyword: string, related: string[]): string {
  const text = `${keyword} ${related.join(" ")}`.toLowerCase();
  if (/buy|price|pricing|review|best|alternative|vs/u.test(text)) {
    return "commercial evaluation";
  }
  if (/how|what|why|guide|tutorial/u.test(text)) {
    return "informational research";
  }
  return "topic exploration";
}

function titleCase(value: string): string {
  return value.replace(/\w\S*/gu, (word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase());
}
